#!/usr/bin/python

nAma_list = [
    ############################################################################
    ['विश्वम्', 'viśvam', 'जो स्वतःच विश्वरूप आहे', 'He who is universe himself'],
    ['विष्णुः', 'viṣṇuḥ', 'जो सर्वत्र व्याप्त आहे', 'He who pervades everywhere'],
    ['वषट्कारः', 'vaṣaṭkāraḥ', 'ज्याला उद्देशून यज्ञात वषट् केला जातो', 'On whose account oblations are offered in fire'],
    ['भूतभव्यभवत्प्रभुः', 'bhūtabhavyabhavatprabhuḥ', 'भूत, भविष्य आणि वर्तमान यांचा स्वामी', 'He who is lord of the past, future and present'],
    ['भूतकृत्', 'bhūtakṛt', 'जो सर्व भुतांची रचना करणारा आहे', 'He who creates all beings'],
    ['भूतभृत्', 'bhūtabhṛt', 'जो सर्व भुतांचे भरण-पोषण करणारा आहे', 'He who nourishes all beings'],
    ['भावः', 'bhāvaḥ', 'जो केवळ अस्तित्वात आहे', 'He who is in sole existence'],
    ['भूतात्मा', 'bhūtātmā', 'जो सर्व भूतांचा आत्मा आहे', 'He who is self of all beings'],
    ['भूतभावनः', 'bhūtabhāvanaḥ', 'जो सर्व भूतांची वृद्धी करणारा आहे', 'He who causes growth of all beings'],
    ############################################################################
    ['पूतात्मा', 'pūtātmā', 'जो पवित्र आत्मा आहे', 'He who is pure self'],
    ['परमात्मा', 'paramātmā', 'जो श्रेष्ठ आत्मा आहे', 'He who is the supreme self'],
    ['मुक्तानां परमा गतिः', 'muktānāṃ paramā gatiḥ', 'जो मुक्त पुरुषांची श्रेष्ठ गति आहे', 'He who is the supreme goal of liberated souls'],
    ['अव्ययः', 'avyayaḥ', 'ज्याचा विनाश होत नाही', 'He who is indestructible'],
    ['पुरुषः', 'puruṣaḥ', 'जो शरीरात शयन करणारा आहे', 'He who reclines in body'],
    ['साक्षी', 'sākṣī', 'जो सर्वकाही पाहणारा आहे', 'He who sees everything'],
    ['क्षेत्रज्ञः', 'kṣetrajñaḥ', 'जो शरीराला जाणणारा आहे', 'He who knows the body'],
    ['अक्षरः', 'akṣaraḥ', 'ज्याचा ह्रास होत नाही', 'He who is undecaying'],
    ############################################################################
    ['योगः', 'yogaḥ', 'जो योगाने जाणल्या जाणारा आहे', 'He who is realized through yoga'],
    ['योगविदां नेता', 'yogavidāṃ netā', 'जो योग जाणणाऱ्यांचा नेता आहे', 'He who is the leader of those who knows yoga'],
    ['प्रधानपुरुषेश्वरः', 'pradhānapuruṣeśvaraḥ', 'जो प्रकृती आणि पुरुष यांचा स्वामी आहे', 'He who is the lord of Prakriti and Purusha'],
    ['नारसिंहवपुः', 'nārasiṃhavapuḥ', 'जो नर आणि सिंह यांचे स्वरूप असणारा आहे', 'He who has the form of man and lion'],
    ['श्रीमान्', 'śrīmān', 'ज्याच्यापाशी श्री नित्य विद्यमान आहे', 'He who is always with Shree'],
    ['केशवः', 'keśavaḥ', 'ज्याचे केश सुंदर आहेत', 'He who has beautiful hairs'],
    ['पुरुषोत्तमः', 'puruṣottamaḥ', 'जो पुरुषांमध्ये उत्तम आहे', 'He who is the best among all Purushas'],
    ############################################################################
    ['सर्वः', 'sarvaḥ', 'He who is everything'],
    ['शर्वः', 'śarvaḥ', 'The auspicious'],
    ['शिवः', 'śivaḥ', 'He who is eternally pure'],
    ['स्थाणुः', 'sthāṇuḥ', 'The pillar, the immovable truth'],
    ['भूतादिः', 'bhūtādiḥ', 'The cause of the five great elements'],
    ['निधिरव्ययः', 'nidhiravyayaḥ', 'The imperishable treasure'],
    ['सम्भवः', 'sambhavaḥ', 'He who descends of His own free will'],
    ['भावनः', 'bhāvanaḥ', 'He who gives everything to his devotees'],
    ['भर्ता', 'bhartā', 'He who nourishes the entire living world'],
    ['प्रभवः', 'prabhavaḥ', 'The womb of the five great elements'],
    ['प्रभुः', 'prabhuḥ', 'The Almighty Lord'],
    ['ईश्वरः', 'īśvaraḥ', 'The Ruler of Universe'],
    ['स्वयम्भूः', 'svayambhūḥ', 'He who manifests from Himself'],
    ['शम्भुः', 'śambhuḥ', 'He who brings auspiciousness'],
    ['आदित्यः', 'ādityaḥ', 'The son of Aditi (Vaamana)'],
    ['पुष्कराक्षः', 'puṣkarākṣaḥ', 'He who has eyes like the lotus'],
    ['महास्वनः', 'mahāsvanaḥ', 'He who has a thundering voice'],
    ['अनादि-निधनः', 'anādi-nidhanaḥ', 'He without origin or end'],
    ['धाता', 'dhātā', 'He who supports all fields of experience'],
    ['विधाता', 'vidhātā', 'The dispenser of fruits of action'],
    ['धातुरुत्तमः', 'dhāturuttamaḥ', 'The subtlest atom'],
    ['अप्रमेयः', 'aprameyaḥ', 'He who cannot be perceived'],
    ['हृषीकेशः', 'hṛṣīkeśaḥ', 'The Lord of the senses'],
    ['पद्मनाभः', 'padmanābhaḥ', 'He from whose navel comes the lotus'],
    ['अमरप्रभुः', 'amaraprabhuḥ', 'The Lord of the devas'],
    ['विश्वकर्मा', 'viśvakarmā', 'The creator of the universe'],
    ['मनुः', 'manuḥ', 'He who has manifested as the Vedic mantras'],
    ['त्वष्टा', 'tvaṣṭā', 'He who makes huge things small'],
    ['स्थविष्ठः', 'sthaviṣṭhaḥ', 'The supremely gross'],
    ['स्थविरो ध्रुवः', 'sthaviro dhruvaḥ', 'The ancient, motionless one'],
    ['अग्राह्यः', 'agrāhyaḥ', 'He who is not perceived by senses'],
    ['शाश्वतः', 'śāśvataḥ', 'He who always remains the same'],
    ['कृष्णः', 'kṛṣṇaḥ', 'He whose complexion is dark'],
    ['लोहिताक्षः', 'lohitākṣaḥ', 'Red-eyed'],
    ['प्रतर्दनः', 'pratardanaḥ', 'The Supreme destruction'],
    ['प्रभूतस्', 'prabhūtas', 'Ever-full'],
    ['त्रिकाकुब्धाम', 'trikākubdhāma', 'The support of the three quarters'],
    ['पवित्रम्', 'pavitram', 'He who gives purity to the heart'],
    ['मंगलं-परम्', 'maṃgalaṃ-param', 'The Supreme auspiciousness'],
    ['ईशानः', 'īśānaḥ', 'The controller of the five great elements'],
    ['प्राणदः', 'prāṇadaḥ', 'He who gives life'],
    ['प्राणः', 'prāṇaḥ', 'He who ever lives'],
    ['ज्येष्ठः', 'jyeṣṭhaḥ', 'Older than all'],
    ['श्रेष्ठः', 'śreṣṭhaḥ', 'The most glorious'],
    ['प्रजापतिः', 'prajāpatiḥ', 'The Lord of all creatures'],
    ['हिरण्यगर्भः', 'hiraṇyagarbhaḥ', 'He who is the golden womb'],
    ['भूगर्भः', 'bhūgarbhaḥ', 'He who is the womb of the earth'],
    ['माधवः', 'mādhavaḥ', 'He who is sweet like honey'],
    ['मधुसूदनः', 'madhusūdanaḥ', 'Destroyer of the Madhu demon'],
    ['ईश्वरः', 'īśvaraḥ', 'The controller'],
    ['विक्रमी', 'vikramī', 'He who is full of prowess'],
    ['धन्वी', 'dhanvī', 'He who always has a divine bow'],
    ['मेधावी', 'medhāvī', 'Supremely intelligent'],
    ['विक्रमः', 'vikramaḥ', 'Valorous'],
    ['क्रमः', 'kramaḥ', 'All-pervading'],
    ['अनुत्तमः', 'anuttamaḥ', 'Incomparably great'],
    ['दुराधर्षः', 'durādharṣaḥ', 'He who cannot be attacked successfully'],
    ['कृतज्ञः', 'kṛtajñaḥ', 'He who knows all that is'],
    ['कृतिः', 'kṛtiḥ', 'He who rewards all our actions'],
    ['आत्मवान्', 'ātmavān', 'The self in all beings'],
    ['सुरेशः', 'sureśaḥ', 'The Lord of the devas'],
    ['शरणम्', 'śaraṇam', 'The refuge'],
    ['शर्म', 'śarma', 'He who is Himself infinite bliss'],
    ['विश्वरेताः', 'viśvaretāḥ', 'The seed of the universe'],
    ['प्रजाभवः', 'prajābhavaḥ', 'He from whom all praja (population) comes'],
    ['अहः', 'ahaḥ', 'He who is the nature of time'],
    ['संवत्सरः', 'saṃvatsaraḥ', 'He from whom the concept of time comes'],
    ['व्यालः', 'vyālaḥ', 'The serpent (vyaalah) to atheists'],
    ['प्रत्ययः', 'pratyayaḥ', 'He whose nature is knowledge'],
    ['सर्वदर्शनः', 'sarvadarśanaḥ', 'All-seeing'],
    ['अजः', 'ajaḥ', 'Unborn'],
    ['सर्वेश्वरः', 'sarveśvaraḥ', 'Controller of all'],
    ['सिद्धः', 'siddhaḥ', 'The most famous'],
    ['सिद्धिः', 'siddhiḥ', 'He who gives moksha'],
    ['सर्वादिः', 'sarvādiḥ', 'The beginning of all'],
    ['अच्युतः', 'acyutaḥ', 'Infallible'],
    ['वृषाकपिः', 'vṛṣākapiḥ', 'He who lifts the world to dharma'],
    ['अमेयात्मा', 'ameyātmā', 'He who manifests in infinite varieties'],
    ['सर्वयोगविनिसृतः', 'sarvayogavinisṛtaḥ', 'He who is free from all attachments'],
    ['वसुः', 'vasuḥ', 'The support of all elements'],
    ['वसुमनाः', 'vasumanāḥ', 'He whose mind is supremely pure'],
    ['सत्यः', 'satyaḥ', 'The truth'],
    ['समात्मा', 'samātmā', 'He who is the same in all'],
    ['सम्मितः', 'sammitaḥ', 'He who has been accepted by authorities'],
    ['समः', 'samaḥ', 'Equal'],
    ['अमोघः', 'amoghaḥ', 'Ever useful'],
    ['पुण्डरीकाक्षः', 'puṇḍarīkākṣaḥ', 'He who dwells in the heart'],
    ['वृषकर्मा', 'vṛṣakarmā', 'He whose every act is righteous'],
    ['वृषाकृतिः', 'vṛṣākṛtiḥ', 'The form of dharma'],
    ['रुद्रः', 'rudraḥ', 'He who is mightiest of the mighty or He who is "fierce"'],
    ['बहुशिरः', 'bahuśiraḥ', 'He who has many heads'],
    ['बभ्रुः', 'babhruḥ', 'He who rules over all the worlds'],
    ['विश्वयोनिः', 'viśvayoniḥ', 'The womb of the universe'],
    ['शुचिश्रवाः', 'śuciśravāḥ', 'He who listens only the good and pure'],
    ['अमृतः', 'amṛtaḥ', 'Immortal'],
    ['शाश्वतः-स्थाणुः', 'śāśvataḥ-sthāṇuḥ', 'Permanent and immovable'],
    ['वरारोहः', 'varārohaḥ', 'The most glorious destination'],
    ['महातपः', 'mahātapaḥ', 'He of great tapas'],
    ['सर्वगः', 'sarvagaḥ', 'All-pervading'],
    ['सर्वविद्भानुः', 'sarvavidbhānuḥ', 'All-knowing and effulgent'],
    ['विष्वक्सेनः', 'viṣvaksenaḥ', 'He against whom no army can stand'],
    ['जनार्दनः', 'janārdanaḥ', 'He who gives joy to good people'],
    ['वेदः', 'vedaḥ', 'He who is the Vedas'],
    ['वेदविद्', 'vedavid', 'The knower of the Vedas'],
    ['अव्यंगः', 'avyaṃgaḥ', 'Without imperfections'],
    ['वेदांगः', 'vedāṃgaḥ', 'He whose limbs are the Vedas'],
    ['वेदवित्', 'vedavit', 'He who contemplates upon the Vedas'],
    ['कविः', 'kaviḥ', 'The seer'],
    ['लोकाध्यक्षः', 'lokādhyakṣaḥ', 'He who presides over all lokas'],
    ['सुराध्यक्षः', 'surādhyakṣaḥ', 'He who presides over all devas'],
    ['धर्माध्यक्षः', 'dharmādhyakṣaḥ', 'He who presides over dharma'],
    ['कृताकृतः', 'kṛtākṛtaḥ', 'All that is created and not created'],
    ['चतुरात्मा', 'caturātmā', 'The four-fold self'],
    ['चतुर्व्यूहः', 'caturvyūhaḥ', 'Vasudeva, Sankarshan etc.'],
    ['चतुर्दंष्ट्रः', 'caturdaṃṣṭraḥ', 'He who has four canines (Nrsimha)'],
    ['चतुर्भुजः', 'caturbhujaḥ', 'Four-handed'],
    ['भ्राजिष्णुः', 'bhrājiṣṇuḥ', 'Self-effulgent consciousness'],
    ['भोजनम्', 'bhojanam', 'He who is the sense-objects'],
    ['भोक्ता', 'bhoktā', 'The enjoyer'],
    ['सहिष्णुः', 'sahiṣṇuḥ', 'He who can suffer patiently'],
    ['जगदादिजः', 'jagadādijaḥ', 'Born at the beginning of the world'],
    ['अनघः', 'anaghaḥ', 'Sinless'],
    ['विजयः', 'vijayaḥ', 'Victorious'],
    ['जेता', 'jetā', 'Ever-successful'],
    ['विश्वयोनिः', 'viśvayoniḥ', 'He who incarnates because of the world'],
    ['पुनर्वसुः', 'punarvasuḥ', 'He who lives repeatedly in different bodies'],
    ['उपेन्द्रः', 'upendraḥ', 'The younger brother of Indra (Vamana)'],
    ['वामनः', 'vāmanaḥ', 'He with a dwarf body'],
    ['प्रांशुः', 'prāṃśuḥ', 'He with a huge body'],
    ['अमोघः', 'amoghaḥ', 'He whose acts are for a great purpose'],
    ['शुचिः', 'śuciḥ', 'He who is spotlessly clean'],
    ['ऊर्जितः', 'ūrjitaḥ', 'He who has infinite vitality'],
    ['अतीन्द्रः', 'atīndraḥ', 'He who surpasses Indra'],
    ['संग्रहः', 'saṃgrahaḥ', 'He who holds everything together'],
    ['सर्गः', 'sargaḥ', 'He who creates the world from Himself'],
    ['धृतात्मा', 'dhṛtātmā', 'Established in Himself'],
    ['नियमः', 'niyamaḥ', 'The appointing authority'],
    ['यमः', 'yamaḥ', 'The administrator'],
    ['वेद्यः', 'vedyaḥ', 'That which is to be known'],
    ['वैद्यः', 'vaidyaḥ', 'The Supreme doctor'],
    ['सदायोगी', 'sadāyogī', 'Always in yoga'],
    ['वीरहा', 'vīrahā', 'He who destroys the mighty heroes'],
    ['माधवः', 'mādhavaḥ', 'The Lord of all knowledge'],
    ['मधुः', 'madhuḥ', 'Sweet'],
    ['अतीन्द्रियः', 'atīndriyaḥ', 'Beyond the sense organs'],
    ['महामायः', 'mahāmāyaḥ', 'The Supreme Master of all Maya'],
    ['महोत्साहः', 'mahotsāhaḥ', 'The great enthusiast'],
    ['महाबलः', 'mahābalaḥ', 'He who has supreme strength'],
    ['महाबुद्धिः', 'mahābuddhiḥ', 'He who has supreme intelligence'],
    ['महावीर्यः', 'mahāvīryaḥ', 'The supreme essence'],
    ['महाशक्तिः', 'mahāśaktiḥ', 'All-powerful'],
    ['महाद्युतिः', 'mahādyutiḥ', 'Greatly luminous'],
    ['अनिर्देश्यवपुः', 'anirdeśyavapuḥ', 'He whose form is indescribable'],
    ['श्रीमान्', 'śrīmān', 'He who is always courted by glories'],
    ['अमेयात्मा', 'ameyātmā', 'He whose essence is immeasurable'],
    ['महाद्रिधृक्', 'mahādridhṛk', 'He who supports the great mountain'],
    ['महेष्वासः', 'maheṣvāsaḥ', 'He who wields shaarnga'],
    ['महीभर्ता', 'mahībhartā', 'The husband of mother earth'],
    ['श्रीनिवासः', 'śrīnivāsaḥ', 'The permanent abode of Shree'],
    ['सतां गतिः', 'satāṃ gatiḥ', 'The goal for all virtuous people'],
    ['अनिरुद्धः', 'aniruddhaḥ', 'He who cannot be obstructed'],
    ['सुरानन्दः', 'surānandaḥ', 'He who gives out happiness'],
    ['गोविन्दः', 'govindaḥ', 'The protector of the Cows.'],
    ['गोविदां-पतिः', 'govidāṃ-patiḥ', 'The Lord of all men of wisdom'],
    ['मरीचिः', 'marīciḥ', 'Effulgence'],
    ['दमनः', 'damanaḥ', 'He who controls rakshasas'],
    ['हंसः', 'haṃsaḥ', 'The swan'],
    ['सुपर्णः', 'suparṇaḥ', 'Beautiful-winged (Two birds analogy)'],
    ['भुजगोत्तमः', 'bhujagottamaḥ', 'The serpent Ananta'],
    ['हिरण्यनाभः', 'hiraṇyanābhaḥ', 'He who has a golden navel'],
    ['सुतपाः', 'sutapāḥ', 'He who has glorious tapas'],
    ['पद्मनाभः', 'padmanābhaḥ', 'He whose navel is like a lotus'],
    ['प्रजापतिः', 'prajāpatiḥ', 'He from whom all creatures emerge'],
    ['अमृत्युः', 'amṛtyuḥ', 'He who knows no death'],
    ['सर्वदृक्', 'sarvadṛk', 'The seer of everything'],
    ['सिंहः', 'siṃhaḥ', 'He who destroys'],
    ['सन्धाता', 'sandhātā', 'The regulator'],
    ['सन्धिमान्', 'sandhimān', 'He who seems to be conditioned'],
    ['स्थिरः', 'sthiraḥ', 'Steady'],
    ['अजः', 'ajaḥ', 'He who takes the form of Aja, Brahma'],
    ['दुर्मषणः', 'durmaṣaṇaḥ', 'He who cannot be vanquished'],
    ['शास्ता', 'śāstā', 'He who rules over the universe'],
    ['विश्रुतात्मा', 'viśrutātmā', 'He who is celebrated, most famous and heard about by one and all.'],
    ['सुरारिहा', 'surārihā', 'Destroyer of the enemies of the devas'],
    ['गुरुः', 'guruḥ', 'The teacher'],
    ['गुरुतमः', 'gurutamaḥ', 'The greatest teacher'],
    ['धाम', 'dhāma', 'The goal'],
    ['सत्यः', 'satyaḥ', 'He who is Himself the truth'],
    ['सत्यपराक्रमः', 'satyaparākramaḥ', 'Dynamic Truth'],
    ['निमिषः', 'nimiṣaḥ', 'He who has closed eyes in contemplation'],
    ['अनिमिषः', 'animiṣaḥ', 'He who remains unwinking; ever knowing'],
    ['स्रग्वी', 'sragvī', 'He who always wears a garland of undecaying flowers'],
    ['वाचस्पतिः-उदारधीः', 'vācaspatiḥ-udāradhīḥ', 'He who is eloquent in championing the Supreme law of life; He with a large-hearted intelligence'],
    ['अग्रणीः', 'agraṇīḥ', 'He who guides us to the peak'],
    ['ग्रामणीः', 'grāmaṇīḥ', 'He who leads the flock'],
    ['श्रीमान्', 'śrīmān', 'The possessor of light, effulgence, glory'],
    ['न्यायः', 'nyāyaḥ', 'Justice'],
    ['नेता', 'netā', 'The leader'],
    ['समीरणः', 'samīraṇaḥ', 'He who sufficiently administers all movements of all living creatures'],
    ['सहस्रमूर्धा', 'sahasramūrdhā', 'He who has endless heads'],
    ['विश्वात्मा', 'viśvātmā', 'The soul of the universe'],
    ['सहस्राक्षः', 'sahasrākṣaḥ', 'Thousands of eyes'],
    ['सहस्रपात्', 'sahasrapāt', 'Thousand-footed'],
    ['आवर्तनः', 'āvartanaḥ', 'The unseen dynamism'],
    ['निवृत्तात्मा', 'nivṛttātmā', 'The soul retreated from matter'],
    ['संवृतः', 'saṃvṛtaḥ', 'He who is veiled from the jiva'],
    ['संप्रमर्दनः', 'saṃpramardanaḥ', 'He who persecutes evil men'],
    ['अहः संवर्तकः', 'ahaḥ saṃvartakaḥ', 'He who thrills the day and makes it function vigorously'],
    ['वह्निः', 'vahniḥ', 'Fire'],
    ['अनिलः', 'anilaḥ', 'Air'],
    ['धरणीधरः', 'dharaṇīdharaḥ', 'He who supports the earth'],
    ['सुप्रसादः', 'suprasādaḥ', 'Fully satisfied'],
    ['प्रसन्नात्मा', 'prasannātmā', 'Ever pure and all-blissful self'],
    ['विश्वधृक्', 'viśvadhṛk', 'Supporter of the world'],
    ['विश्वभुक्', 'viśvabhuk', 'He who enjoys all experiences'],
    ['विभुः', 'vibhuḥ', 'He who manifests in endless forms'],
    ['सत्कर्ता', 'satkartā', 'He who adores good and wise people'],
    ['सत्कृतः', 'satkṛtaḥ', 'He who is adored by all good people'],
    ['साधुः', 'sādhuḥ', 'He who lives by the righteous codes'],
    ['जह्नुः', 'jahnuḥ', 'Leader of men'],
    ['नारायणः', 'nārāyaṇaḥ', 'He who resides on the waters'],
    ['नरः', 'naraḥ', 'The guide'],
    ['असंख्येयः', 'asaṃkhyeyaḥ', 'He who has numberless names and forms'],
    ['अप्रमेयात्मा', 'aprameyātmā', 'A soul not known through the pramanas'],
    ['विशिष्टः', 'viśiṣṭaḥ', 'He who transcends all in His glory'],
    ['शिष्टकृत्', 'śiṣṭakṛt', 'The lawmaker'],
    ['शुचिः', 'śuciḥ', 'He who is pure'],
    ['सिद्धार्थः', 'siddhārthaḥ', 'He who has all arthas'],
    ['सिद्धसंकल्पः', 'siddhasaṃkalpaḥ', 'He who gets all He wishes for'],
    ['सिद्धिदः', 'siddhidaḥ', 'The giver of benedictions'],
    ['सिद्धिसाधनः', 'siddhisādhanaḥ', 'The power behind our sadhana'],
    ['वृषाही', 'vṛṣāhī', 'Controller of all actions'],
    ['वृषभः', 'vṛṣabhaḥ', 'He who showers all dharmas'],
    ['विष्णुः', 'viṣṇuḥ', 'Long-striding'],
    ['वृषपर्वा', 'vṛṣaparvā', 'The ladder leading to dharma (As well as dharma itself)'],
    ['वृषोदरः', 'vṛṣodaraḥ', 'He from whose belly life showers forth'],
    ['वर्धनः', 'vardhanaḥ', 'The nurturer and nourisher'],
    ['वर्धमानः', 'vardhamānaḥ', 'He who can grow into any dimension'],
    ['विविक्तः', 'viviktaḥ', 'Separate'],
    ['श्रुतिसागरः', 'śrutisāgaraḥ', 'The ocean for all scripture'],
    ['सुभुजः', 'subhujaḥ', 'He who has graceful arms'],
    ['दुर्धरः', 'durdharaḥ', 'He who cannot be known by great yogis'],
    ['वाग्मी', 'vāgmī', 'He who is eloquent in speech'],
    ['महेन्द्रः', 'mahendraḥ', 'The lord of Indra'],
    ['वसुदः', 'vasudaḥ', 'He who gives all wealth'],
    ['वसुः', 'vasuḥ', 'He who is Wealth'],
    ['नैकरूपः', 'naikarūpaḥ', 'He who has unlimited forms'],
    ['बृहद्रूपः', 'bṛhadrūpaḥ', 'Vast, of infinite dimensions'],
    ['शिपिविष्टः', 'śipiviṣṭaḥ', 'The presiding deity of the sun'],
    ['प्रकाशनः', 'prakāśanaḥ', 'He who illuminates'],
    ['ओजस्तेजोद्युतिधरः', 'ojastejodyutidharaḥ', 'The possessor of vitality, effulgence and beauty'],
    ['प्रकाशात्मा', 'prakāśātmā', 'The effulgent self'],
    ['प्रतापनः', 'pratāpanaḥ', 'Thermal energy; one who heats'],
    ['ऋद्धः', 'ṛddhaḥ', 'Full of prosperity'],
    ['स्पष्टाक्षरः', 'spaṣṭākṣaraḥ', 'One who is indicated by OM'],
    ['मन्त्रः', 'mantraḥ', 'The nature of the Vedic mantras'],
    ['चन्द्रांशुः', 'candrāṃśuḥ', 'The rays of the moon'],
    ['भास्करद्युतिः', 'bhāskaradyutiḥ', 'The effulgence of the sun'],
    ['अमृतांशोद्भवः', 'amṛtāṃśodbhavaḥ', 'The Paramatman from whom Amrutamshu or the Moon originated at the time of the churning of the Milk-ocean.[27]'],
    ['भानुः', 'bhānuḥ', 'Self-effulgent'],
    ['शशबिन्दुः', 'śaśabinduḥ', 'The moon who has a rabbit-like spot'],
    ['सुरेश्वरः', 'sureśvaraḥ', 'A person of extreme charity'],
    ['औषधम्', 'auṣadham', 'Medicine'],
    ['जगतः सेतुः', 'jagataḥ setuḥ', 'A bridge across the material energy'],
    ['सत्यधर्मपराक्रमः', 'satyadharmaparākramaḥ', 'One who champions heroically for truth and righteousness'],
    ['भूतभव्यभवन्नाथः', 'bhūtabhavyabhavannāthaḥ', 'The Lord of past, present and future'],
    ['पवनः', 'pavanaḥ', 'The air that fills the universe'],
    ['पावनः', 'pāvanaḥ', 'He who gives life-sustaining power to air'],
    ['अनलः', 'analaḥ', 'Fire'],
    ['कामहा', 'kāmahā', 'He who destroys all desires'],
    ['कामकृत्', 'kāmakṛt', 'He who fulfills all desires'],
    ['कान्तः', 'kāntaḥ', 'He who is of enchanting form'],
    ['कामः', 'kāmaḥ', 'The beloved'],
    ['कामप्रदः', 'kāmapradaḥ', 'He who supplies desired objects'],
    ['प्रभुः', 'prabhuḥ', 'The Lord'],
    ['युगादिकृत्', 'yugādikṛt', 'The creator of the yugas'],
    ['युगावर्तः', 'yugāvartaḥ', 'The law behind time'],
    ['नैकमायः', 'naikamāyaḥ', 'He whose forms are endless and varied'],
    ['महाशनः', 'mahāśanaḥ', 'He who eats up everything'],
    ['अदृश्यः', 'adṛśyaḥ', 'Imperceptible'],
    ['व्यक्तरूपः', 'vyaktarūpaḥ', 'He who is perceptible to the yogi'],
    ['सहस्रजित्', 'sahasrajit', 'He who vanquishes thousands'],
    ['अनन्तजित्', 'anantajit', 'Ever-victorious'],
    ['इष्टः', 'iṣṭaḥ', 'He who is invoked through Vedic rituals'],
    ['विशिष्टः', 'viśiṣṭaḥ', 'The noblest and most sacred'],
    ['शिष्टेष्टः', 'śiṣṭeṣṭaḥ', 'The greatest beloved'],
    ['शिखंडी', 'śikhaṃḍī', 'Incarnation as Lord Krishna with a peacock feather embedded in his crown. Shikhandee'],
    ['नहुषः', 'nahuṣaḥ', 'He who binds all with maya'],
    ['वृषः', 'vṛṣaḥ', 'He who is dharma'],
    ['क्रोधहा', 'krodhahā', 'He who destroys anger'],
    ['क्रोधकृत्कर्ता', 'krodhakṛtkartā', 'He who generates anger against the lower tendency'],
    ['विश्वबाहुः', 'viśvabāhuḥ', 'He whose hand is in everything'],
    ['महीधरः', 'mahīdharaḥ', 'The support of the earth'],
    ['अच्युतः', 'acyutaḥ', 'He who undergoes no changes'],
    ['प्रथितः', 'prathitaḥ', 'He who exists pervading all'],
    ['प्राणः', 'prāṇaḥ', 'The\xa0prana\xa0in all living creatures'],
    ['प्राणदः', 'prāṇadaḥ', 'He who gives\xa0prana'],
    ['वासवानुजः', 'vāsavānujaḥ', 'The brother of Indra'],
    ['अपां-निधिः', 'apāṃ-nidhiḥ', 'Treasure of waters (the ocean)'],
    ['अधिष्ठानम्', 'adhiṣṭhānam', 'The substratum of the entire universe'],
    ['अप्रमत्तः', 'apramattaḥ', 'He who never makes a wrong judgement'],
    ['प्रतिष्ठितः', 'pratiṣṭhitaḥ', 'He who has no cause'],
    ['स्कन्दः', 'skandaḥ', 'He whose glory is expressed through Subrahmanya'],
    ['स्कन्दधरः', 'skandadharaḥ', 'Upholder of withering righteousness'],
    ['धूर्यः', 'dhūryaḥ', 'Who carries out creation etc. without hitch'],
    ['वरदः', 'varadaḥ', 'He who fulfills boons'],
    ['वायुवाहनः', 'vāyuvāhanaḥ', 'Controller of winds'],
    ['वासुदेवः', 'vāsudevaḥ', 'Dwelling in all creatures although not affected by that condition'],
    ['बृहद्भानुः', 'bṛhadbhānuḥ', 'He who illumines the world with the rays of the sun and moon'],
    ['आदिदेवः', 'ādidevaḥ', 'The primary source of everything'],
    ['पुरन्दरः', 'purandaraḥ', 'Destroyer of cities'],
    ['अशोकः', 'aśokaḥ', 'He who has no sorrow'],
    ['तारणः', 'tāraṇaḥ', 'He who enables others to cross'],
    ['तारः', 'tāraḥ', 'He who saves'],
    ['शूरः', 'śūraḥ', 'The valiant'],
    ['शौरिः', 'śauriḥ', 'He who incarnated in the dynasty of Shoora'],
    ['जनेश्वरः', 'janeśvaraḥ', 'The Lord of the people'],
    ['अनुकूलः', 'anukūlaḥ', 'Well-wisher of everyone'],
    ['शतावर्तः', 'śatāvartaḥ', 'He who takes infinite forms'],
    ['पद्मी', 'padmī', 'He who holds a lotus'],
    ['पद्मनिभेक्षणः', 'padmanibhekṣaṇaḥ', 'Lotus-eyed'],
    ['पद्मनाभः', 'padmanābhaḥ', 'He who has a lotus-navel'],
    ['अरविन्दाक्षः', 'aravindākṣaḥ', 'He who has eyes as beautiful as the lotus'],
    ['पद्मगर्भः', 'padmagarbhaḥ', 'He who is being meditated upon in the lotus of the heart'],
    ['शरीरभृत्', 'śarīrabhṛt', 'He who sustains all bodies'],
    ['महर्द्धिः', 'maharddhiḥ', 'One who has great prosperity'],
    ['ऋद्धः', 'ṛddhaḥ', 'He who has expanded Himself as the universe'],
    ['वृद्धात्मा', 'vṛddhātmā', 'The ancient self'],
    ['महाक्षः', 'mahākṣaḥ', 'The great-eyed'],
    ['गरुडध्वजः', 'garuḍadhvajaḥ', 'One who has Garuda on His flag'],
    ['अतुलः', 'atulaḥ', 'Incomparable'],
    ['शरभः', 'śarabhaḥ', 'One who dwells and shines forth through the bodies'],
    ['भीमः', 'bhīmaḥ', 'The terrible'],
    ['समयज्ञः', 'samayajñaḥ', 'One whose worship is nothing more than keeping an equal vision of the mind by the devotee'],
    ['हविर्हरिः', 'havirhariḥ', 'The receiver of all oblation'],
    ['सर्वलक्षणलक्षण्यः', 'sarvalakṣaṇalakṣaṇyaḥ', 'Known through all proofs'],
    ['लक्ष्मीवान्', 'lakṣmīvān', 'The consort of Laksmi'],
    ['समितिञ्जयः', 'samitiñjayaḥ', 'Ever-victorious'],
    ['विक्षरः', 'vikṣaraḥ', 'Imperishable'],
    ['रोहितः', 'rohitaḥ', 'The fish incarnation'],
    ['मार्गः', 'mārgaḥ', 'The path'],
    ['हेतुः', 'hetuḥ', 'The cause'],
    ['दामोदरः', 'dāmodaraḥ', 'Who has a rope around his stomach'],
    ['सहः', 'sahaḥ', 'All-enduring'],
    ['महीधरः', 'mahīdharaḥ', 'The bearer of the earth'],
    ['महाभागः', 'mahābhāgaḥ', 'He who gets the greatest share in every Yajna'],
    ['वेगवान्', 'vegavān', 'He who is swift'],
    ['अमिताशनः', 'amitāśanaḥ', 'Of endless appetite'],
    ['उद्भवः', 'udbhavaḥ', 'The originator'],
    ['क्षोभणः', 'kṣobhaṇaḥ', 'The agitator'],
    ['देवः', 'devaḥ', 'He who revels'],
    ['श्रीगर्भः', 'śrīgarbhaḥ', 'He in whom are all glories'],
    ['परमेश्वरः', 'parameśvaraḥ', 'Parama + Ishvara = Supreme Lord, Parama (MahaLakshmi i.e. above all the shaktis) + Ishvara (Lord) = Lord of MahaLakshmi'],
    ['करणम्', 'karaṇam', 'The instrument'],
    ['कारणम्', 'kāraṇam', 'The cause'],
    ['कर्ता', 'kartā', 'The doer'],
    ['विकर्ता', 'vikartā', 'Creator of the endless varieties that make up the universe'],
    ['गहनः', 'gahanaḥ', 'The unknowable'],
    ['गुहः', 'guhaḥ', 'He who dwells in the cave of the heart'],
    ['व्यवसायः', 'vyavasāyaḥ', 'Resolute'],
    ['व्यवस्थानः', 'vyavasthānaḥ', 'The substratum'],
    ['संस्थानः', 'saṃsthānaḥ', 'The ultimate authority'],
    ['स्थानदः', 'sthānadaḥ', 'He who confers the right abode'],
    ['ध्रुवः', 'dhruvaḥ', 'The changeless in the midst of changes'],
    ['परर्धिः', 'parardhiḥ', 'He who has supreme manifestations'],
    ['परमस्पष्टः', 'paramaspaṣṭaḥ', 'The extremely vivid'],
    ['तुष्टः', 'tuṣṭaḥ', 'One who is contented with a very simple offering'],
    ['पुष्टः', 'puṣṭaḥ', 'One who is ever-full'],
    ['शुभेक्षणः', 'śubhekṣaṇaḥ', 'All-auspicious gaze'],
    ['रामः', 'rāmaḥ', 'One who is most handsome'],
    ['विरामः', 'virāmaḥ', 'The abode of perfect-rest'],
    ['विरजः', 'virajaḥ', 'Passionless'],
    ['मार्गः', 'mārgaḥ', 'The path'],
    ['नेयः', 'neyaḥ', 'The guide'],
    ['नयः', 'nayaḥ', 'One who leads'],
    ['अनयः', 'anayaḥ', 'One who has no leader'],
    ['वीरः', 'vīraḥ', 'The valiant'],
    ['शक्तिमतां श्रेष्ठः', 'śaktimatāṃ śreṣṭhaḥ', 'The best among the powerful'],
    ['धर्मः', 'dharmaḥ', 'The law of being'],
    ['धर्मविदुत्तमः', 'dharmaviduttamaḥ', 'The highest among men of realisation'],
    ['वैकुण्ठः', 'vaikuṇṭhaḥ', 'Lord of supreme abode, Vaikuntha'],
    ['पुरुषः', 'puruṣaḥ', 'One who dwells in all bodies'],
    ['प्राणः', 'prāṇaḥ', 'Life'],
    ['प्राणदः', 'prāṇadaḥ', 'Giver of life'],
    ['प्रणवः', 'praṇavaḥ', 'He who is praised by the gods'],
    ['पृथुः', 'pṛthuḥ', 'The expanded'],
    ['हिरण्यगर्भः', 'hiraṇyagarbhaḥ', 'The creator'],
    ['शत्रुघ्नः', 'śatrughnaḥ', 'The destroyer of enemies'],
    ['व्याप्तः', 'vyāptaḥ', 'The pervader'],
    ['वायुः', 'vāyuḥ', 'The air'],
    ['अधोक्षजः', 'adhokṣajaḥ', 'One whose vitality never flows downwards'],
    ['ऋतुः', 'ṛtuḥ', 'The seasons'],
    ['सुदर्शनः', 'sudarśanaḥ', 'He whose meeting is auspicious'],
    ['कालः', 'kālaḥ', 'He who judges and punishes beings'],
    ['परमेष्ठी', 'parameṣṭhī', 'One who is readily available for experience within the heart'],
    ['परिग्रहः', 'parigrahaḥ', 'The receiver'],
    ['उग्रः', 'ugraḥ', 'The terrible'],
    ['संवत्सरः', 'saṃvatsaraḥ', 'The year'],
    ['दक्षः', 'dakṣaḥ', 'The smart'],
    ['विश्रामः', 'viśrāmaḥ', 'The resting place'],
    ['विश्वदक्षिणः', 'viśvadakṣiṇaḥ', 'The most skilful and efficient'],
    ['विस्तारः', 'vistāraḥ', 'The extension'],
    ['स्थावरस्स्थाणुः', 'sthāvarassthāṇuḥ', 'The firm and motionless'],
    ['प्रमाणम्', 'pramāṇam', 'The proof'],
    ['बीजमव्ययम्', 'bījamavyayam', 'The Immutable Seed'],
    ['अर्थः', 'arthaḥ', 'He who is worshiped by all'],
    ['अनर्थः', 'anarthaḥ', 'One to whom there is nothing yet to be fulfilled'],
    ['महाकोशः', 'mahākośaḥ', 'He who has got around him great sheaths'],
    ['महाभोगः', 'mahābhogaḥ', 'He who is of the nature of enjoyment'],
    ['महाधनः', 'mahādhanaḥ', 'He who is supremely rich'],
    ['अनिर्विण्णः', 'anirviṇṇaḥ', 'He who has no discontent'],
    ['स्थविष्ठः', 'sthaviṣṭhaḥ', 'One who is supremely huge'],
    ['अभूः', 'abhūḥ', 'One who has no birth'],
    ['धर्मयूपः', 'dharmayūpaḥ', 'The post to which all dharma is tied'],
    ['महामखः', 'mahāmakhaḥ', 'The great sacrificer'],
    ['नक्षत्रनेमिः', 'nakṣatranemiḥ', 'The nave of the stars'],
    ['नक्षत्री', 'nakṣatrī', 'The Lord of the stars (the moon)'],
    ['क्षमः', 'kṣamaḥ', 'He who is supremely efficient in all undertakings'],
    ['क्षामः', 'kṣāmaḥ', 'He who ever remains without any scarcity'],
    ['समीहनः', 'samīhanaḥ', 'One whose desires are auspicious'],
    ['यज्ञः', 'yajñaḥ', 'One who is of the nature of yajna'],
    ['इज्यः', 'ijyaḥ', 'He who is fit to be invoked through yajna'],
    ['महेज्यः', 'mahejyaḥ', 'One who is to be most worshiped'],
    ['क्रतुः', 'kratuḥ', 'The animal-sacrifice'],
    ['सत्रम्', 'satram', 'Protector of the good'],
    ['सतां-गतिः', 'satāṃ-gatiḥ', 'Refuge of the good'],
    ['सर्वदर्शी', 'sarvadarśī', 'All-knower'],
    ['विमुक्तात्मा', 'vimuktātmā', 'The ever-liberated self'],
    ['सर्वज्ञः', 'sarvajñaḥ', 'Omniscient'],
    ['ज्ञानमुत्तमम्', 'jñānamuttamam', 'The Supreme Knowledge'],
    ['सुव्रतः', 'suvrataḥ', 'He who ever-performing the pure vow'],
    ['सुमुखः', 'sumukhaḥ', 'One who has a charming face'],
    ['सूक्ष्मः', 'sūkṣmaḥ', 'The subtlest'],
    ['सुघोषः', 'sughoṣaḥ', 'Of auspicious sound'],
    ['सुखदः', 'sukhadaḥ', 'Giver of happiness'],
    ['सुहृत्', 'suhṛt', 'Friend of all creatures'],
    ['मनोहरः', 'manoharaḥ', 'The stealer of the mind'],
    ['जितक्रोधः', 'jitakrodhaḥ', 'One who has conquered anger'],
    ['वीरबाहुः', 'vīrabāhuḥ', 'Having mighty arms'],
    ['विदारणः', 'vidāraṇaḥ', 'One who splits asunder'],
    ['स्वापनः', 'svāpanaḥ', 'One who puts people to sleep'],
    ['स्ववशः', 'svavaśaḥ', 'He who has everything under His control'],
    ['व्यापी', 'vyāpī', 'All-pervading'],
    ['नैकात्मा', 'naikātmā', 'Many souled'],
    ['नैककर्मकृत्', 'naikakarmakṛt', 'One who does many actions'],
    ['वत्सरः', 'vatsaraḥ', 'The abode'],
    ['वत्सलः', 'vatsalaḥ', 'The supremely affectionate'],
    ['वत्सी', 'vatsī', 'The father'],
    ['रत्नगर्भः', 'ratnagarbhaḥ', 'The jewel-wombed'],
    ['धनेश्वरः', 'dhaneśvaraḥ', 'The Lord of wealth'],
    ['धर्मगुब्', 'dharmagub', 'One who protects dharma'],
    ['धर्मकृत्', 'dharmakṛt', 'One who acts according to dharma'],
    ['धर्मी', 'dharmī', 'The supporter of dharma'],
    ['सत्', 'sat', 'existence'],
    ['असत्', 'asat', 'illusion'],
    ['क्षरम्', 'kṣaram', 'He who appears to perish'],
    ['अक्षरम्', 'akṣaram', 'Imperishable'],
    ['अविज्ञाता', 'avijñātā', 'The non-knower (The knower being the conditioned soul within the body)'],
    ['सहस्रांशुः', 'sahasrāṃśuḥ', 'The thousand-rayed'],
    ['विधाता', 'vidhātā', 'All supporter'],
    ['कृतलक्षणः', 'kṛtalakṣaṇaḥ', 'One who is famous for His qualities'],
    ['गभस्तिनेमिः', 'gabhastinemiḥ', 'The hub of the universal wheel'],
    ['सत्त्वस्थः', 'sattvasthaḥ', 'Situated in sattva'],
    ['सिंहः', 'siṃhaḥ', 'The lion'],
    ['भूतमहेश्वरः', 'bhūtamaheśvaraḥ', 'The great lord of beings'],
    ['आदिदेवः', 'ādidevaḥ', 'The first deity'],
    ['महादेवः', 'mahādevaḥ', 'The great deity'],
    ['देवेशः', 'deveśaḥ', 'The Lord of all devas'],
    ['देवभृद्गुरुः', 'devabhṛdguruḥ', 'Advisor of Indra'],
    ['उत्तरः', 'uttaraḥ', 'He who lifts us from the ocean of samsara'],
    ['गोपतिः', 'gopatiḥ', 'The shepherd'],
    ['गोप्ता', 'goptā', 'The protector'],
    ['ज्ञानगम्यः', 'jñānagamyaḥ', 'One who is experienced through pure knowledge'],
    ['पुरातनः', 'purātanaḥ', 'He who was even before time'],
    ['शरीरभूतभृत्', 'śarīrabhūtabhṛt', 'One who nourishes the nature from which the bodies came'],
    ['भोक्ता', 'bhoktā', 'The enjoyer'],
    ['कपीन्द्रः', 'kapīndraḥ', 'Lord of the monkeys (Rama)'],
    ['भूरिदक्षिणः', 'bhūridakṣiṇaḥ', 'He who gives away large gifts'],
    ['सोमपः', 'somapaḥ', 'One who takes Soma in the yajnas'],
    ['अमृतपः', 'amṛtapaḥ', 'One who drinks the nectar'],
    ['सोमः', 'somaḥ', 'One who as the moon nourishes plants'],
    ['पुरुजित्', 'purujit', 'One who has conquered numerous enemies'],
    ['पुरुसत्तमः', 'purusattamaḥ', 'The greatest of the great'],
    ['विनयः', 'vinayaḥ', 'He who humiliates those who are unrighteous'],
    ['जयः', 'jayaḥ', 'The victorious'],
    ['सत्यसन्धः', 'satyasandhaḥ', 'Of truthful resolution'],
    ['दाशार्हः', 'dāśārhaḥ', 'One who was born in the Dasarha race'],
    ['सात्त्वतां पतिः', 'sāttvatāṃ patiḥ', 'The Lord of the Satvatas'],
    ['जीवः', 'jīvaḥ', 'One who functions as the ksetrajna'],
    ['विनयितासाक्षी', 'vinayitāsākṣī', 'The witness of modesty'],
    ['मुकुन्दः', 'mukundaḥ', 'The giver of liberation'],
    ['अमितविक्रमः', 'amitavikramaḥ', 'Of immeasurable prowess'],
    ['अम्भोनिधिः', 'ambhonidhiḥ', 'The substratum of the four types of beings'],
    ['अनन्तात्मा', 'anantātmā', 'The infinite self'],
    ['महोदधिशयः', 'mahodadhiśayaḥ', 'One who rests on the great ocean'],
    ['अन्तकः', 'antakaḥ', 'The death'],
    ['अजः', 'ajaḥ', 'Unborn'],
    ['महार्हः', 'mahārhaḥ', 'One who deserves the highest worship'],
    ['स्वाभाव्यः', 'svābhāvyaḥ', 'Ever rooted in the nature of His own self'],
    ['जितामित्रः', 'jitāmitraḥ', 'One who has conquered all enemies'],
    ['प्रमोदनः', 'pramodanaḥ', 'Ever-blissful'],
    ['आनन्दः', 'ānandaḥ', 'A mass of pure bliss'],
    ['नन्दनः', 'nandanaḥ', 'One who makes others blissful'],
    ['नन्दः', 'nandaḥ', 'Free from all worldly pleasures'],
    ['सत्यधर्मा', 'satyadharmā', 'One who has in Himself all true dharmas'],
    ['त्रिविक्रमः', 'trivikramaḥ', 'One who took three steps'],
    ['महर्षिः कपिलाचार्यः', 'maharṣiḥ kapilācāryaḥ', 'He who incarnated as Kapila, the great sage'],
    ['कृतज्ञः', 'kṛtajñaḥ', 'The knower of the creation'],
    ['मेदिनीपतिः', 'medinīpatiḥ', 'The Lord of the earth'],
    ['त्रिपदः', 'tripadaḥ', 'One who has taken three steps'],
    ['त्रिदशाध्यक्षः', 'tridaśādhyakṣaḥ', 'The Lord of the three states of consciousness'],
    ['महाशृंगः', 'mahāśṛṃgaḥ', 'Great-horned (Matsya)'],
    ['कृतान्तकृत्', 'kṛtāntakṛt', 'Destroyer of the creation'],
    ['महावराहः', 'mahāvarāhaḥ', 'The great boar'],
    ['गोविन्दः', 'govindaḥ', 'One who is known through Vedanta'],
    ['सुषेणः', 'suṣeṇaḥ', 'He who has a charming army'],
    ['कनकांगदी', 'kanakāṃgadī', 'Wearer of bright-as-gold armlets'],
    ['गुह्यः', 'guhyaḥ', 'The mysterious'],
    ['गभीरः', 'gabhīraḥ', 'The unfathomable'],
    ['गहनः', 'gahanaḥ', 'Impenetrable'],
    ['गुप्तः', 'guptaḥ', 'The well-concealed'],
    ['चक्रगदाधरः', 'cakragadādharaḥ', 'Bearer of the disc and mace'],
    ['वेधाः', 'vedhāḥ', 'Creator of the universe'],
    ['स्वांगः', 'svāṃgaḥ', 'One with well-proportioned limbs'],
    ['अजितः', 'ajitaḥ', 'Vanquished by none'],
    ['कृष्णः', 'kṛṣṇaḥ', 'Dark-complexioned'],
    ['दृढः', 'dṛḍhaḥ', 'The firm'],
    ['संकर्षणोऽच्युतः', 'saṃkarṣaṇo’cyutaḥ', 'He who absorbs the whole creation into His nature and never falls away from that nature'],
    ['वरुणः', 'varuṇaḥ', 'One who sets on the horizon (Sun)'],
    ['वारुणः', 'vāruṇaḥ', 'The son of Varuna (Vasistha or Agastya)'],
    ['वृक्षः', 'vṛkṣaḥ', 'The tree'],
    ['पुष्कराक्षः', 'puṣkarākṣaḥ', 'Lotus eyed'],
    ['महामनः', 'mahāmanaḥ', 'Great-minded'],
    ['भगवान्', 'bhagavān', 'One who possesses six opulences'],
    ['भगहा', 'bhagahā', 'One who destroys the six opulences during pralaya'],
    ['आनन्दी', 'ānandī', 'One who gives delight'],
    ['वनमाली', 'vanamālī', 'One who wears a garland of forest flowers'],
    ['हलायुधः', 'halāyudhaḥ', 'One who has a plough as His weapon'],
    ['आदित्यः', 'ādityaḥ', 'Son of Aditi'],
    ['ज्योतिरादित्यः', 'jyotirādityaḥ', 'The resplendence of the sun'],
    ['सहिष्णुः', 'sahiṣṇuḥ', 'One who calmly endures duality'],
    ['गतिसत्तमः', 'gatisattamaḥ', 'The ultimate refuge for all devotees'],
    ['सुधन्वा', 'sudhanvā', 'One who has Shaarnga'],
    ['खण्डपरशु:', 'khaṇḍaparaśu:', 'One who holds an axe'],
    ['दारुणः', 'dāruṇaḥ', 'Merciless towards the unrighteous'],
    ['द्रविणप्रदः', 'draviṇapradaḥ', 'One who lavishly gives wealth'],
    ['दिवःस्पृक्', 'divaḥspṛk', 'Sky-reaching'],
    ['सर्वदृग्व्यासः', 'sarvadṛgvyāsaḥ', 'One who creates many men of wisdom'],
    ['वाचस्पतिरयोनिजः', 'vācaspatirayonijaḥ', 'One who is the master of all vidyas and who is unborn through a womb'],
    ['त्रिसामा', 'trisāmā', 'One who is glorified by Devas, Vratas and Saamans'],
    ['सामगः', 'sāmagaḥ', 'The singer of the sama songs'],
    ['साम', 'sāma', 'The Sama Veda'],
    ['निर्वाणम्', 'nirvāṇam', 'All-bliss'],
    ['भेषजम्', 'bheṣajam', 'Medicine'],
    ['भृषक्', 'bhṛṣak', 'Physician'],
    ['संन्यासकृत्', 'saṃnyāsakṛt', 'Institutor of sannyasa'],
    ['समः', 'samaḥ', 'Calm'],
    ['शान्तः', 'śāntaḥ', 'Peaceful within'],
    ['निष्ठा', 'niṣṭhā', 'Abode of all beings'],
    ['शान्तिः', 'śāntiḥ', 'One whose very nature is peace'],
    ['परायणम्', 'parāyaṇam', 'The way to liberation'],
    ['शुभांगः', 'śubhāṃgaḥ', 'One who has the most beautiful form'],
    ['शान्तिदः', 'śāntidaḥ', 'Giver of peace'],
    ['स्रष्टा', 'sraṣṭā', 'Creator of all beings'],
    ['कुमुदः', 'kumudaḥ', 'He who delights in the earth'],
    ['कुवलेशयः', 'kuvaleśayaḥ', 'He who reclines in the waters'],
    ['गोहितः', 'gohitaḥ', 'One who does welfare for cows'],
    ['गोपतिः', 'gopatiḥ', 'Husband of the earth'],
    ['गोप्ता', 'goptā', 'Protector of the universe'],
    ['वृषभाक्षः', 'vṛṣabhākṣaḥ', 'One whose eyes rain fulfilment of desires'],
    ['वृषप्रियः', 'vṛṣapriyaḥ', 'One who delights in dharma'],
    ['अनिवर्ती', 'anivartī', 'One who never retreats'],
    ['निवृतात्मा', 'nivṛtātmā', 'One who is fully restrained from all sense indulgences'],
    ['संक्षेप्ता', 'saṃkṣeptā', 'The involver'],
    ['क्षेमकृत्', 'kṣemakṛt', 'Doer of good'],
    ['शिवः', 'śivaḥ', 'Auspiciousness'],
    ['श्रीवत्सवत्साः', 'śrīvatsavatsāḥ', 'One who has sreevatsa on His chest'],
    ['श्रीवासः', 'śrīvāsaḥ', 'Abode of Sree'],
    ['श्रीपतिः', 'śrīpatiḥ', 'Lord of Laksmi'],
    ['श्रीमतां वरः', 'śrīmatāṃ varaḥ', 'The best among glorious'],
    ['श्रीदः', 'śrīdaḥ', 'Giver of opulence'],
    ['श्रीशः', 'śrīśaḥ', 'The Lord of Sree'],
    ['श्रीनिवासः', 'śrīnivāsaḥ', 'One who dwells in the good people'],
    ['श्रीनिधिः', 'śrīnidhiḥ', 'The treasure of Sree'],
    ['श्रीविभावनः', 'śrīvibhāvanaḥ', 'Distributor of Sree'],
    ['श्रीधरः', 'śrīdharaḥ', 'Holder of Sree'],
    ['श्रीकरः', 'śrīkaraḥ', 'One who gives Sree'],
    ['श्रेयः', 'śreyaḥ', 'Liberation'],
    ['श्रीमान्', 'śrīmān', 'Possessor of Sree'],
    ['लोकत्रयाश्रयः', 'lokatrayāśrayaḥ', 'Shelter of the three worlds'],
    ['स्वक्षः', 'svakṣaḥ', 'Beautiful-eyed'],
    ['स्वङ्गः', 'svaṅgaḥ', 'Beautiful-limbed'],
    ['शतानन्दः', 'śatānandaḥ', 'Of infinite varieties and joys'],
    ['नन्दिः', 'nandiḥ', 'Infinite bliss'],
    ['ज्योतिर्गणेश्वरः', 'jyotirgaṇeśvaraḥ', 'Lord of the luminaries in the cosmos'],
    ['विजितात्मा', 'vijitātmā', 'One who has conquered the sense organs'],
    ['विधेयात्मा', 'vidheyātmā', 'One who is ever available for the devotees to command in love'],
    ['सत्कीर्तिः', 'satkīrtiḥ', 'One of pure fame'],
    ['छिन्नसंशयः', 'chinnasaṃśayaḥ', 'One whose doubts are ever at rest'],
    ['उदीर्णः', 'udīrṇaḥ', 'The great transcendent'],
    ['सर्वतश्चक्षुः', 'sarvataścakṣuḥ', 'One who has eyes everywhere'],
    ['अनीशः', 'anīśaḥ', 'One who has none to Lord over Him'],
    ['शाश्वतः-स्थिरः', 'śāśvataḥ-sthiraḥ', 'One who is eternal and stable'],
    ['भूशयः', 'bhūśayaḥ', 'One who rested on the ocean shore (Rama)'],
    ['भूषणः', 'bhūṣaṇaḥ', 'One who adorns the world'],
    ['भूतिः', 'bhūtiḥ', 'One who is pure existence'],
    ['विशोकः', 'viśokaḥ', 'Sorrowless'],
    ['शोकनाशनः', 'śokanāśanaḥ', 'Destroyer of sorrows'],
    ['अर्चिष्मान्', 'arciṣmān', 'The effulgent'],
    ['अर्चितः', 'arcitaḥ', 'One who is constantly worshipped by His devotees'],
    ['कुम्भः', 'kumbhaḥ', 'The pot within whom everything is contained'],
    ['विशुद्धात्मा', 'viśuddhātmā', 'One who has the purest soul'],
    ['विशोधनः', 'viśodhanaḥ', 'The great purifier'],
    ['अनिरुद्धः', 'aniruddhaḥ', 'He who is invincible by any enemy'],
    ['अप्रतिरथः', 'apratirathaḥ', 'One who has no enemies to threaten Him'],
    ['प्रद्युम्नः', 'pradyumnaḥ', 'Very rich'],
    ['अमितविक्रमः', 'amitavikramaḥ', 'Of immeasurable prowess'],
    ['कालनेमीनिहा', 'kālanemīnihā', 'Slayer of\xa0Kalanemi'],
    ['वीरः', 'vīraḥ', 'The heroic victor'],
    ['शौरी', 'śaurī', 'One who always has invincible prowess'],
    ['शूरजनेश्वरः', 'śūrajaneśvaraḥ', 'Lord of the valiant'],
    ['त्रिलोकात्मा', 'trilokātmā', 'The self of the three worlds'],
    ['त्रिलोकेशः', 'trilokeśaḥ', 'The Lord of the three worlds'],
    ['केशवः', 'keśavaḥ', 'One whose rays illumine the cosmos'],
    ['केशिहा', 'keśihā', 'Killer of\xa0Keshi'],
    ['हरिः', 'hariḥ', 'The creator'],
    ['कामदेवः', 'kāmadevaḥ', 'The beloved Lord'],
    ['कामपालः', 'kāmapālaḥ', 'The fulfiller of desires'],
    ['कामी', 'kāmī', 'One who has fulfilled all His desires'],
    ['कान्तः', 'kāntaḥ', 'Of enchanting form'],
    ['कृतागमः', 'kṛtāgamaḥ', 'The author of the agama scriptures'],
    ['अनिर्देश्यवपुः', 'anirdeśyavapuḥ', 'Of Indescribable form'],
    ['विष्णुः', 'viṣṇuḥ', 'All-pervading'],
    ['वीरः', 'vīraḥ', 'The courageous'],
    ['अनन्तः', 'anantaḥ', 'Endless'],
    ['धनञ्जयः', 'dhanañjayaḥ', 'One who gained wealth through conquest'],
    ['ब्रह्मण्यः', 'brahmaṇyaḥ', 'Protector of Brahman (anything related to Narayana)'],
    ['ब्रह्मकृत्', 'brahmakṛt', 'One who acts in Brahman'],
    ['ब्रह्मा', 'brahmā', 'Creator'],
    ['ब्रहम', 'brahama', 'Biggest'],
    ['ब्रह्मविवर्धनः', 'brahmavivardhanaḥ', 'One who increases the Brahman'],
    ['ब्रह्मविद्', 'brahmavid', 'One who knows Brahman'],
    ['ब्राह्मणः', 'brāhmaṇaḥ', 'One who has realised Brahman'],
    ['ब्रह्मी', 'brahmī', 'One who is with Brahma'],
    ['ब्रह्मज्ञः', 'brahmajñaḥ', 'One who knows the nature of Brahman'],
    ['ब्राह्मणप्रियः', 'brāhmaṇapriyaḥ', 'Dear to the brahmanas'],
    ['महाकर्मः', 'mahākarmaḥ', 'Of great step'],
    ['महाकर्मा', 'mahākarmā', 'One who performs great deeds'],
    ['महातेजा', 'mahātejā', 'One of great resplendence'],
    ['महोरगः', 'mahoragaḥ', 'The great serpent'],
    ['महाक्रतुः', 'mahākratuḥ', 'The great sacrifice'],
    ['महायज्वा', 'mahāyajvā', 'One who performed great yajnas'],
    ['महायज्ञः', 'mahāyajñaḥ', 'The great yajna'],
    ['महाहविः', 'mahāhaviḥ', 'The great offering'],
    ['स्तव्यः', 'stavyaḥ', 'One who is the object of all praise'],
    ['स्तवप्रियः', 'stavapriyaḥ', 'One who is invoked through prayer'],
    ['स्तोत्रम्', 'stotram', 'The hymn'],
    ['स्तुतिः', 'stutiḥ', 'The act of praise'],
    ['स्तोता', 'stotā', 'One who adores or praises'],
    ['रणप्रियः', 'raṇapriyaḥ', 'Lover of battles'],
    ['पूर्णः', 'pūrṇaḥ', 'The complete'],
    ['पूरयिता', 'pūrayitā', 'The fulfiller'],
    ['पुण्यः', 'puṇyaḥ', 'The truly holy'],
    ['पुण्यकीर्तिः', 'puṇyakīrtiḥ', 'Of Holy fame'],
    ['अनामयः', 'anāmayaḥ', 'One who has no diseases'],
    ['मनोजवः', 'manojavaḥ', 'Swift as the mind'],
    ['तीर्थकरः', 'tīrthakaraḥ', 'The teacher of the tirthas'],
    ['वसुरेताः', 'vasuretāḥ', 'He whose essence is golden'],
    ['वसुप्रदः', 'vasupradaḥ', 'The free-giver of wealth'],
    ['वसुप्रदः', 'vasupradaḥ', 'The giver of salvation, the greatest wealth'],
    ['वासुदेवः', 'vāsudevaḥ', 'The son of Vasudeva'],
    ['वसुः', 'vasuḥ', 'The refuge for all'],
    ['वसुमना', 'vasumanā', 'One who is attentive to everything'],
    ['हविः', 'haviḥ', 'The oblation'],
    ['सद्गतिः', 'sadgatiḥ', 'The goal of good people'],
    ['सत्कृतिः', 'satkṛtiḥ', 'One who is full of Good actions'],
    ['सत्ता', 'sattā', 'One without a second'],
    ['सद्भूतिः', 'sadbhūtiḥ', 'One who has rich glories'],
    ['सत्परायणः', 'satparāyaṇaḥ', 'The Supreme goal for the good'],
    ['शूरसेनः', 'śūrasenaḥ', 'One who has heroic and valiant armies'],
    ['यदुश्रेष्ठः', 'yaduśreṣṭhaḥ', 'The best among the Yadava clan'],
    ['सन्निवासः', 'sannivāsaḥ', 'The abode of the good'],
    ['सुयामुनः', 'suyāmunaḥ', 'One who attended by the people dwelling on the banks of Yamuna'],
    ['भूतावासः', 'bhūtāvāsaḥ', 'The dwelling place of the elements'],
    ['वासुदेवः', 'vāsudevaḥ', 'One who envelops the world with Maya'],
    ['सर्वासुनिलयः', 'sarvāsunilayaḥ', 'The abode of all life energies'],
    ['अनलः', 'analaḥ', 'One of unlimited wealth, power and glory'],
    ['दर्पहा', 'darpahā', 'The destroyer of pride in evil-minded people'],
    ['दर्पदः', 'darpadaḥ', 'One who creates pride, or an urge to be the best, among the righteous'],
    ['दृप्तः', 'dṛptaḥ', 'One who is drunk with Infinite bliss'],
    ['दुर्धरः', 'durdharaḥ', 'The object of contemplation'],
    ['अथापराजितः', 'athāparājitaḥ', 'The unvanquished'],
    ['विश्वमूर्तिः', 'viśvamūrtiḥ', 'Of the form of the entire Universe'],
    ['महामूर्तिः', 'mahāmūrtiḥ', 'The great form'],
    ['दीप्तमूर्तिः', 'dīptamūrtiḥ', 'Of resplendent form'],
    ['अमूर्तिमान्', 'amūrtimān', 'Having no form'],
    ['अनेकमूर्तिः', 'anekamūrtiḥ', 'Multi-formed'],
    ['अव्यक्तः', 'avyaktaḥ', 'Unmanifeset'],
    ['शतमूर्तिः', 'śatamūrtiḥ', 'Of many forms'],
    ['शताननः', 'śatānanaḥ', 'Many-faced'],
    ['एकः', 'ekaḥ', 'The one'],
    ['नैकः', 'naikaḥ', 'The many'],
    ['सवः', 'savaḥ', 'The nature of the sacrifice'],
    ['कः', 'kaḥ', 'One who is of the nature of bliss'],
    ['किम्', 'kim', 'What (the one to be inquired into)'],
    ['यत्', 'yat', 'Which'],
    ['तत्', 'tat', 'That'],
    ['पदमनुत्तमम्', 'padamanuttamam', 'The unequalled state of perfection'],
    ['लोकबन्धुः', 'lokabandhuḥ', 'Friend of the world'],
    ['लोकनाथः', 'lokanāthaḥ', 'Lord of the world'],
    ['माधवः', 'mādhavaḥ', 'Born in the family of Madhu'],
    ['भक्तवत्सलः', 'bhaktavatsalaḥ', 'One who loves His devotees'],
    ['सुवर्णवर्णः', 'suvarṇavarṇaḥ', 'Golden-coloured'],
    ['हेमांगः', 'hemāṃgaḥ', 'One who has limbs of gold'],
    ['वरांगः', 'varāṃgaḥ', 'With beautiful limbs'],
    ['चन्दनांगदी', 'candanāṃgadī', 'One who has attractive armlets'],
    ['वीरहा', 'vīrahā', 'Destroyer of valiant heroes'],
    ['विषमः', 'viṣamaḥ', 'Unequalled'],
    ['शून्यः', 'śūnyaḥ', 'The void'],
    ['घृताशी', 'ghṛtāśī', 'One who has no need for good wishes'],
    ['अचलः', 'acalaḥ', 'Non-moving'],
    ['चलः', 'calaḥ', 'Moving'],
    ['अमानी', 'amānī', 'Without false vanity'],
    ['मानदः', 'mānadaḥ', 'One who causes, by His maya, false identification with the body'],
    ['मान्यः', 'mānyaḥ', 'One who is to be honoured'],
    ['लोकस्वामी', 'lokasvāmī', 'Lord of the universe'],
    ['त्रिलोकधृक्', 'trilokadhṛk', 'One who is the support of all the three worlds'],
    ['सुमेधा', 'sumedhā', 'One who has pure intelligence'],
    ['मेधजः', 'medhajaḥ', 'Born out of sacrifices'],
    ['धन्यः', 'dhanyaḥ', 'Fortunate'],
    ['सत्यमेधः', 'satyamedhaḥ', 'One whose intelligence never fails'],
    ['धराधरः', 'dharādharaḥ', 'The sole support of the earth'],
    ['तेजोवृषः', 'tejovṛṣaḥ', 'One who showers radiance'],
    ['द्युतिधरः', 'dyutidharaḥ', 'One who bears an effulgent form'],
    ['सर्वशस्त्रभृतां वरः', 'sarvaśastrabhṛtāṃ varaḥ', 'The best among those who wield weapons'],
    ['प्रग्रहः', 'pragrahaḥ', 'Receiver of worship'],
    ['निग्रहः', 'nigrahaḥ', 'The killer'],
    ['व्यग्रः', 'vyagraḥ', "One who is ever engaged in fulfilling the devotee's desires"],
    ['नैकशृंगः', 'naikaśṛṃgaḥ', 'One who has many horns'],
    ['गदाग्रजः', 'gadāgrajaḥ', 'One who is invoked through mantra'],
    ['चतुर्मूर्तिः', 'caturmūrtiḥ', 'Four-formed'],
    ['चतुर्बाहुः', 'caturbāhuḥ', 'Four-handed'],
    ['चतुर्व्यूहः', 'caturvyūhaḥ', 'One who expresses Himself as the dynamic centre in the four vyoohas'],
    ['चतुर्गतिः', 'caturgatiḥ', 'The ultimate goal of all four varnas and asramas'],
    ['चतुरात्मा', 'caturātmā', 'Clear-minded'],
    ['चतुर्भावः', 'caturbhāvaḥ', 'The source of the four'],
    ['चतुर्वेदविद्', 'caturvedavid', 'Knower of all four vedas'],
    ['एकपात्', 'ekapāt', 'One-footed (BG 10.42)'],
    ['समावर्तः', 'samāvartaḥ', 'The efficient turner'],
    ['निवृत्तात्मा', 'nivṛttātmā', 'One whose mind is turned away from sense indulgence'],
    ['दुर्जयः', 'durjayaḥ', 'The invincible'],
    ['दुरतिक्रमः', 'duratikramaḥ', 'One who is difficult to be disobeyed'],
    ['दुर्लभः', 'durlabhaḥ', 'One who can be obtained with great efforts'],
    ['दुर्गमः', 'durgamaḥ', 'One who is realised with great effort'],
    ['दुर्गः', 'durgaḥ', 'Not easy to storm into'],
    ['दुरावासः', 'durāvāsaḥ', 'Not easy to lodge'],
    ['दुरारिहा', 'durārihā', 'Slayer of the asuras'],
    ['शुभांगः', 'śubhāṃgaḥ', 'One with enchanting limbs'],
    ['लोकसारंगः', 'lokasāraṃgaḥ', 'One who understands the universe'],
    ['सुतन्तुः', 'sutantuḥ', 'Beautifully expanded'],
    ['तन्तुवर्धनः', 'tantuvardhanaḥ', 'One who sustains the continuity of the drive for the family'],
    ['इन्द्रकर्मा', 'indrakarmā', 'One who always performs gloriously auspicious actions'],
    ['महाकर्मा', 'mahākarmā', 'One who accomplishes great acts'],
    ['कृतकर्मा', 'kṛtakarmā', 'One who has fulfilled his acts'],
    ['कृतागमः', 'kṛtāgamaḥ', 'Author of the Vedas'],
    ['उद्भवः', 'udbhavaḥ', 'The ultimate source'],
    ['सुन्दरः', 'sundaraḥ', 'Of unrivalled beauty'],
    ['सुन्दः', 'sundaḥ', 'Of great mercy'],
    ['रत्ननाभः', 'ratnanābhaḥ', 'Of beautiful navel'],
    ['सुलोचनः', 'sulocanaḥ', 'One who has the most enchanting eyes'],
    ['अर्कः', 'arkaḥ', 'One who is in the form of the sun'],
    ['वाजसनः', 'vājasanaḥ', 'The giver of food'],
    ['शृंगी', 'śṛṃgī', 'The horned one'],
    ['जयन्तः', 'jayantaḥ', 'The conqueror of all enemies'],
    ['सर्वविज्जयी', 'sarvavijjayī', 'One who is at once omniscient and victorious'],
    ['सुवर्णबिन्दुः', 'suvarṇabinduḥ', 'With limbs radiant like gold'],
    ['अक्षोभ्यः', 'akṣobhyaḥ', 'One who is ever unruffled'],
    ['सर्ववागीश्वरेश्वरः', 'sarvavāgīśvareśvaraḥ', 'Lord of the Lord of speech'],
    ['महाहृदः', 'mahāhṛdaḥ', 'One who is like a great refreshing swimming pool'],
    ['महागर्तः', 'mahāgartaḥ', 'The great chasm'],
    ['महाभूतः', 'mahābhūtaḥ', 'The great being'],
    ['महानिधिः', 'mahānidhiḥ', 'The great abode'],
    ['कुमुदः', 'kumudaḥ', 'One who gladdens the earth'],
    ['कुन्दरः', 'kundaraḥ', 'The one who lifted the earth'],
    ['कुन्दः', 'kundaḥ', 'One who is as attractive as Kunda flowers'],
    ['पर्जन्यः', 'parjanyaḥ', 'He who is similar to rain-bearing clouds'],
    ['पावनः', 'pāvanaḥ', 'One who ever purifies'],
    ['अनिलः', 'anilaḥ', 'One who never slips'],
    ['अमृतांशः', 'amṛtāṃśaḥ', 'One whose desires are never fruitless'],
    ['अमृतवपुः', 'amṛtavapuḥ', 'He whose form is immortal'],
    ['सर्वज्ञः', 'sarvajñaḥ', 'Omniscient'],
    ['सर्वतोमुखः', 'sarvatomukhaḥ', 'One who has His face turned everywhere'],
    ['सुलभः', 'sulabhaḥ', 'One who is readily available'],
    ['सुव्रतः', 'suvrataḥ', 'One who has taken the most auspicious forms'],
    ['सिद्धः', 'siddhaḥ', 'One who is perfection'],
    ['शत्रुजित्', 'śatrujit', 'One who is ever victorious over His hosts of enemies'],
    ['शत्रुतापनः', 'śatrutāpanaḥ', 'The scorcher of enemies'],
    ['न्यग्रोधः', 'nyagrodhaḥ', 'The one who veils Himself with Maya'],
    ['उदुम्बरः', 'udumbaraḥ', 'Nourishment of all living creatures'],
    ['अश्वत्थः', 'aśvatthaḥ', 'Tree of life'],
    ['चाणूरान्ध्रनिषूदनः', 'cāṇūrāndhraniṣūdanaḥ', 'The slayer of Canura'],
    ['सहस्रार्चिः', 'sahasrārciḥ', 'He who has thousands of rays'],
    ['सप्तजिह्वः', 'saptajihvaḥ', 'He who expresses himself as the seven tongues of fire (Types of agni)'],
    ['सप्तैधाः', 'saptaidhāḥ', 'The seven effulgences in the flames'],
    ['सप्तवाहनः', 'saptavāhanaḥ', 'One who has a vehicle of seven horses (sun)'],
    ['अमूर्तिः', 'amūrtiḥ', 'Formless'],
    ['अनघः', 'anaghaḥ', 'Sinless'],
    ['अचिन्त्यः', 'acintyaḥ', 'Inconceivable'],
    ['भयकृत्', 'bhayakṛt', 'Giver of fear'],
    ['भयनाशनः', 'bhayanāśanaḥ', 'Destroyer of fear'],
    ['अणुः', 'aṇuḥ', 'The subtlest'],
    ['बृहत्', 'bṛhat', 'The greatest'],
    ['कृशः', 'kṛśaḥ', 'Delicate, lean'],
    ['स्थूलः', 'sthūlaḥ', 'One who is the fattest'],
    ['गुणभृत्', 'guṇabhṛt', 'One who supports'],
    ['निर्गुणः', 'nirguṇaḥ', 'Without any properties'],
    ['महान्', 'mahān', 'The mighty'],
    ['अधृतः', 'adhṛtaḥ', 'Without support'],
    ['स्वधृतः', 'svadhṛtaḥ', 'Self-supported'],
    ['स्वास्यः', 'svāsyaḥ', 'One who has an effulgent face'],
    ['प्राग्वंशः', 'prāgvaṃśaḥ', 'One who has the most ancient ancestry'],
    ['वंशवर्धनः', 'vaṃśavardhanaḥ', 'He who multiplies His family of descendants'],
    ['भारभृत्', 'bhārabhṛt', 'One who carries the load of the universe'],
    ['कथितः', 'kathitaḥ', 'One who is glorified in all scriptures'],
    ['योगी', 'yogī', 'One who can be realised through yoga'],
    ['योगीशः', 'yogīśaḥ', 'The king of yogis'],
    ['सर्वकामदः', 'sarvakāmadaḥ', 'One who fulfils all desires of true devotees'],
    ['आश्रमः', 'āśramaḥ', 'Haven'],
    ['श्रमणः', 'śramaṇaḥ', 'One who persecutes the worldly people'],
    ['क्षामः', 'kṣāmaḥ', 'One who destroys everything'],
    ['सुपर्णः', 'suparṇaḥ', 'The golden leaf (Vedas) BG 15.1'],
    ['वायुवाहनः', 'vāyuvāhanaḥ', 'The mover of the winds'],
    ['धनुर्धरः', 'dhanurdharaḥ', 'The wielder of the bow'],
    ['धनुर्वेदः', 'dhanurvedaḥ', 'One who declared the science of archery'],
    ['दण्डः', 'daṇḍaḥ', 'One who punishes the wicked'],
    ['दमयिता', 'damayitā', 'The controller'],
    ['दमः', 'damaḥ', 'Beautitude in the self'],
    ['अपराजितः', 'aparājitaḥ', 'One who cannot be defeated'],
    ['सर्वसहः', 'sarvasahaḥ', 'One who carries the entire Universe'],
    ['अनियन्ता', 'aniyantā', 'One who has no controller'],
    ['नियमः', 'niyamaḥ', "One who is not under anyone's laws"],
    ['अयमः', 'ayamaḥ', 'One who knows no death'],
    ['सत्त्ववान्', 'sattvavān', 'One who is full of exploits and courage'],
    ['सात्त्विकः', 'sāttvikaḥ', 'One who is full of sattvic qualities'],
    ['सत्यः', 'satyaḥ', 'Truth'],
    ['सत्यधर्मपराक्रमः', 'satyadharmaparākramaḥ', 'One who is the very abode of truth and dharma'],
    ['अभिप्रायः', 'abhiprāyaḥ', 'One who is faced by all seekers marching to the infinite'],
    ['प्रियार्हः', 'priyārhaḥ', 'One who deserves all our love'],
    ['अर्हः', 'arhaḥ', 'One who deserves to be worshiped'],
    ['प्रियकृत्', 'priyakṛt', 'One who is ever-obliging in fulfilling our wishes'],
    ['प्रीतिवर्धनः', 'prītivardhanaḥ', "One who increases joy in the devotee's heart"],
    ['विहायसगतिः', 'vihāyasagatiḥ', 'One who travels in space'],
    ['ज्योतिः', 'jyotiḥ', 'Self-effulgent'],
    ['सुरुचिः', 'suruciḥ', 'Whose desire manifests as the universe'],
    ['हुतभुक्', 'hutabhuk', 'One who enjoys all that is offered in yajna'],
    ['विभुः', 'vibhuḥ', 'All-pervading'],
    ['रविः', 'raviḥ', 'One who dries up everything'],
    ['विरोचनः', 'virocanaḥ', 'One who shines in different forms'],
    ['सूर्यः', 'sūryaḥ', 'The one source from where everything is born'],
    ['सविता', 'savitā', 'The one who brings forth the Universe from Himself'],
    ['रविलोचनः', 'ravilocanaḥ', 'One whose eye is the sun'],
    ['अनन्तः', 'anantaḥ', 'Endless'],
    ['हुतभुक्', 'hutabhuk', 'One who accepts oblations'],
    ['भोक्ता', 'bhoktā', 'One who enjoys'],
    ['सुखदः', 'sukhadaḥ', 'Giver of bliss to those who are liberated'],
    ['नैकजः', 'naikajaḥ', 'One who is born many times'],
    ['अग्रजः', 'agrajaḥ', 'The first amongst eternal [ Pradhana Purusha ]. Agra means first and ajah means never born. Both individual souls and Vishnu are eternal but Ishvara is Pradhana Taatva. Hence the word agra.'],
    ['अनिर्विण्णः', 'anirviṇṇaḥ', 'One who feels no disappointment'],
    ['सदामर्षी', 'sadāmarṣī', 'One who forgives the trespasses of His devotees'],
    ['लोकाधिष्ठानम्', 'lokādhiṣṭhānam', 'The substratum of the universe'],
    ['अद्भुतः', 'adbhutaḥ', 'Wonderful'],
    ['सनात्', 'sanāt', 'The beginningless and endless factor'],
    ['सनातनतमः', 'sanātanatamaḥ', 'The most ancient'],
    ['कपिलः', 'kapilaḥ', 'The great sage Kapila'],
    ['कपिः', 'kapiḥ', 'One who drinks water'],
    ['अव्ययः', 'avyayaḥ', 'The one in whom the universe merges'],
    ['स्वस्तिदः', 'svastidaḥ', 'Giver of Svasti'],
    ['स्वस्तिकृत्', 'svastikṛt', 'One who robs all auspiciousness'],
    ['स्वस्ति', 'svasti', 'One who is the source of all auspiciouness'],
    ['स्वस्तिभुक्', 'svastibhuk', 'One who constantly enjoys auspiciousness'],
    ['स्वस्तिदक्षिणः', 'svastidakṣiṇaḥ', 'Distributor of auspiciousness'],
    ['अरौद्रः', 'araudraḥ', 'One who has no negative emotions or urges'],
    ['कुण्डली', 'kuṇḍalī', 'One who wears shark earrings'],
    ['चक्री', 'cakrī', 'Holder of the chakra'],
    ['विक्रमी', 'vikramī', 'The most daring'],
    ['ऊर्जितशासनः', 'ūrjitaśāsanaḥ', 'One who commands with His hand'],
    ['शब्दातिगः', 'śabdātigaḥ', 'One who transcends all words'],
    ['शब्दसहः', 'śabdasahaḥ', 'One who allows Himself to be invoked by Vedic declarations'],
    ['शिशिरः', 'śiśiraḥ', 'The cold season, winter'],
    ['शर्वरीकरः', 'śarvarīkaraḥ', 'Creator of darkness'],
    ['अक्रूरः', 'akrūraḥ', 'Never cruel'],
    ['पेशलः', 'peśalaḥ', 'One who is supremely soft'],
    ['दक्षः', 'dakṣaḥ', 'Prompt'],
    ['दक्षिणः', 'dakṣiṇaḥ', 'The most liberal'],
    ['क्षमिणांवरः', 'kṣamiṇāṃvaraḥ', 'One who has the greatest amount of patience with sinners'],
    ['विद्वत्तमः', 'vidvattamaḥ', 'One who has the greatest wisdom'],
    ['वीतभयः', 'vītabhayaḥ', 'One with no fear'],
    ['पुण्यश्रवणकीर्तनः', 'puṇyaśravaṇakīrtanaḥ', 'The hearing of whose glory causes holiness to grow'],
    ['उत्तारणः', 'uttāraṇaḥ', 'One who lifts us out of the ocean of change'],
    ['दुष्कृतिहा', 'duṣkṛtihā', 'Destroyer of bad actions'],
    ['पुण्यः', 'puṇyaḥ', 'Supremely pure'],
    ['दुःस्वप्ननाशनः', 'duḥsvapnanāśanaḥ', 'One who destroys all bad dreams'],
    ['वीरहा', 'vīrahā', 'One who ends the passage from womb to womb'],
    ['रक्षणः', 'rakṣaṇaḥ', 'Protector of the universe'],
    ['सन्तः', 'santaḥ', 'One who is expressed through saintly men'],
    ['जीवनः', 'jīvanaḥ', 'The life spark in all creatures'],
    ['पर्यवस्थितः', 'paryavasthitaḥ', 'One who dwells everywhere'],
    ['अनन्तरूपः', 'anantarūpaḥ', 'One of infinite forms'],
    ['अनन्तश्रीः', 'anantaśrīḥ', 'Full of infinite glories'],
    ['जितमन्युः', 'jitamanyuḥ', 'One who has no anger'],
    ['भयापहः', 'bhayāpahaḥ', 'One who destroys all fears'],
    ['चतुरश्रः', 'caturaśraḥ', 'One who deals squarely'],
    ['गभीरात्मा', 'gabhīrātmā', 'Too deep to be fathomed'],
    ['विदिशः', 'vidiśaḥ', 'One who is unique in His giving'],
    ['व्यादिशः', 'vyādiśaḥ', 'One who is unique in His commanding power'],
    ['दिशः', 'diśaḥ', 'One who advises and gives knowledge'],
    ['अनादिः', 'anādiḥ', 'One who is the first cause'],
    ['भूर्भूवः', 'bhūrbhūvaḥ', 'The substratum of the earth'],
    ['लक्ष्मीः', 'lakṣmīḥ', 'The glory of the universe'],
    ['सुवीरः', 'suvīraḥ', 'One who moves through various ways'],
    ['रुचिरांगदः', 'rucirāṃgadaḥ', 'One who wears resplendent shoulder caps'],
    ['जननः', 'jananaḥ', 'He who delivers all living creatures'],
    ['जनजन्मादिः', 'janajanmādiḥ', 'The cause of the birth of all creatures'],
    ['भीमः', 'bhīmaḥ', 'Terrible form'],
    ['भीमपराक्रमः', 'bhīmaparākramaḥ', 'One whose prowess is fearful to His enemies'],
    ['आधारनिलयः', 'ādhāranilayaḥ', 'The fundamental sustainer'],
    ['अधाता', 'adhātā', 'Above whom there is no other to command'],
    ['पुष्पहासः', 'puṣpahāsaḥ', 'He who shines like an opening flower'],
    ['प्रजागरः', 'prajāgaraḥ', 'Ever-awakened'],
    ['ऊर्ध्वगः', 'ūrdhvagaḥ', 'One who is on top of everything'],
    ['सत्पथाचारः', 'satpathācāraḥ', 'One who walks the path of truth'],
    ['प्राणदः', 'prāṇadaḥ', 'Giver of life'],
    ['प्रणवः', 'praṇavaḥ', 'Omkara'],
    ['पणः', 'paṇaḥ', 'The supreme universal manager'],
    ['प्रमाणम्', 'pramāṇam', 'He whose form is the Vedas'],
    ['प्राणनिलयः', 'prāṇanilayaḥ', 'He in whom all\xa0prana\xa0is established'],
    ['प्राणभृत्', 'prāṇabhṛt', 'He who rules over all\xa0pranas'],
    ['प्राणजीवनः', 'prāṇajīvanaḥ', 'He who maintains the life-breath in all living creatures'],
    ['तत्त्वम्', 'tattvam', 'The reality'],
    ['तत्त्वविद्', 'tattvavid', 'One who has realised the reality'],
    ['एकात्मा', 'ekātmā', 'The one self'],
    ['जन्ममृत्युजरातिगः', 'janmamṛtyujarātigaḥ', 'One who knows no birth, death or old age in Himself'],
    ['भूर्भुवःस्वस्तरुः', 'bhūrbhuvaḥsvastaruḥ', 'The tree of the three worlds (bhoo=terrestrial, svah=celestial and bhuvah=the world in between)'],
    ['तारः', 'tāraḥ', 'One who helps all to cross over'],
    ['सविताः', 'savitāḥ', 'The father of all'],
    ['प्रपितामहः', 'prapitāmahaḥ', 'The father of the father of beings (Brahma)'],
    ['यज्ञः', 'yajñaḥ', 'One whose very nature is yajna'],
    ['यज्ञपतिः', 'yajñapatiḥ', 'The Lord of all yajnas'],
    ['यज्वा', 'yajvā', 'The one who performs yajna'],
    ['यज्ञांगः', 'yajñāṃgaḥ', 'One whose limbs are the things employed in yajna'],
    ['यज्ञवाहनः', 'yajñavāhanaḥ', 'One who fulfils yajnas in complete'],
    ['यज्ञभृद्', 'yajñabhṛd', 'The ruler of the yajanas'],
    ['यज्ञकृत्', 'yajñakṛt', 'One who performs yajna'],
    ['यज्ञी', 'yajñī', 'Enjoyer of yajnas'],
    ['यज्ञभुक्', 'yajñabhuk', 'Receiver of all that is offered'],
    ['यज्ञसाधनः', 'yajñasādhanaḥ', 'One who fulfils all yajnas'],
    ['यज्ञान्तकृत्', 'yajñāntakṛt', 'One who performs the concluding act of the yajna'],
    ['यज्ञगुह्यम्', 'yajñaguhyam', 'The person to be realised by yajna'],
    ['अन्नम्', 'annam', 'One who is food'],
    ['अन्नादः', 'annādaḥ', 'One who eats the food'],
    ['आत्मयोनिः', 'ātmayoniḥ', 'The uncaused cause'],
    ['स्वयंजातः', 'svayaṃjātaḥ', 'Self-born'],
    ['वैखानः', 'vaikhānaḥ', 'The one who cut through the earth'],
    ['सामगायनः', 'sāmagāyanaḥ', 'One who sings the sama songs; one who loves hearing saama chants;'],
    ['देवकीनन्दनः', 'devakīnandanaḥ', 'Son of Devaki'],
    ['स्रष्टा', 'sraṣṭā', 'Creator'],
    ['क्षितीशः', 'kṣitīśaḥ', 'The Lord of the earth'],
    ['पापनाशनः', 'pāpanāśanaḥ', 'Destroyer of sin'],
    ['शंखभृत्', 'śaṃkhabhṛt', 'One who has the divine Pancajanya'],
    ['नन्दकी', 'nandakī', 'One who holds the\xa0Nandaka\xa0sword'],
    ['चक्री', 'cakrī', 'Carrier of Sudarshana chakra'],
    ['शार्ङ्गधन्वा', 'śārṅgadhanvā', 'One who aims His shaarnga bow'],
    ['गदाधरः', 'gadādharaḥ', 'Carrier of\xa0Kaumodaki\xa0club'],
    ['रथांगपाणिः', 'rathāṃgapāṇiḥ', 'One who has the wheel of a chariot as His weapon; One with the strings of the chariot in his hands;'],
    ['अक्षोभ्यः', 'akṣobhyaḥ', 'One who cannot be annoyed by anyone'],
    ['सर्वप्रहरणायुधः', 'sarvapraharaṇāyudhaḥ', 'He who has all implements for all kinds of assault and fight']
]
